version: '3'
services:
  backend_api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 8080:80
    networks:
      - appnetwork
    volumes:
      - ./src/api:/app

  frontend:
    build:
      context: ./src/front
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    tty: true
    networks:
      - appnetwork
    volumes:
      - ./src/front:/app

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - appnetwork

networks:
  appnetwork: