version: '3'
services:
  backend_api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 8080:80
    networks:
      - appnetwork

  frontend:
    build:
      context: ./src/front
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    tty: true
    networks:
      - appnetwork

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - appnetwork

networks:
  appnetwork: